[tool.black]
target-version = ['py37']
skip-magic-trailing-comma = true

[tool.pycln]
all = true
exclude = "main\\.py"

[tool.isort]
profile = "black"
combine_as_imports = true
skip_gitignore = true

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"